const keySets = {
    "en":
        [
            [
                { glyph: '`', upperGlyph: '~', color: 'finger-5', size: 'small', code: 192 },
                { glyph: '1', upperGlyph: '!', color: 'finger-5', size: 'key', code: 49 },
                { glyph: '2', upperGlyph: '@', color: 'finger-4', size: 'key', code: 50 },
                { glyph: '3', upperGlyph: '#', color: 'finger-3', size: 'key', code: 51 },
                { glyph: '4', upperGlyph: '$', color: 'finger-2-left', size: 'key', code: 52 },
                { glyph: '5', upperGlyph: '%', color: 'finger-2-left', size: 'key', code: 53 },
                { glyph: '6', upperGlyph: '^', color: 'finger-2-left', size: 'key', code: 54 },
                { glyph: '7', upperGlyph: '&', color: 'finger-2-right', size: 'key', code: 55 },
                { glyph: '8', upperGlyph: '*', color: 'finger-3', size: 'key', code: 56 },
                { glyph: '9', upperGlyph: '(', color: 'finger-4', size: 'key', code: 57 },
                { glyph: '0', upperGlyph: ')', color: 'finger-5', size: 'key', code: 48 },
                { glyph: '-', upperGlyph: '_', color: 'finger-5', size: 'key', code: 189 },
                { glyph: '=', upperGlyph: '+', color: 'finger-5', size: 'key', code: 187 },
                { glyph: 'Backspace', upperGlyph: 'Backspace', color: 'grey', size: 'command', code: 8 }
            ],
            [
                { glyph: 'Tab', upperGlyph: 'Tab', color: 'grey', size: 'command', code: 9 },
                { glyph: 'q', upperGlyph: 'Q', color: 'finger-5', size: 'key', code: 81 },
                { glyph: 'w', upperGlyph: 'W', color: 'finger-4', size: 'key', code: 87 },
                { glyph: 'e', upperGlyph: 'E', color: 'finger-3', size: 'key', code: 69 },
                { glyph: 'r', upperGlyph: 'R', color: 'finger-2-left', size: 'key', code: 82 },
                { glyph: 't', upperGlyph: 'T', color: 'finger-2-left', size: 'key', code: 84 },
                { glyph: 'y', upperGlyph: 'Y', color: 'finger-2-right', size: 'key', code: 89 },
                { glyph: 'u', upperGlyph: 'U', color: 'finger-2-right', size: 'key', code: 85 },
                { glyph: 'i', upperGlyph: 'I', color: 'finger-3', size: 'key', code: 73 },
                { glyph: 'o', upperGlyph: 'O', color: 'finger-4', size: 'key', code: 79 },
                { glyph: 'p', upperGlyph: 'P', color: 'finger-5', size: 'key', code: 80 },
                { glyph: '[', upperGlyph: '{', color: 'finger-5', size: 'key', code: 219 },
                { glyph: ']', upperGlyph: '}', color: 'finger-5', size: 'key', code: 221 },
                { glyph: '\\', upperGlyph: '|', color: 'grey', size: 'command', code: 220 },
            ],
            [
                { glyph: 'Caps Lock', upperGlyph: 'Caps Lock', color: 'grey', size: 'command', code: 20 },
                { glyph: 'a', upperGlyph: 'A', color: 'finger-5', size: 'key', code: 65 },
                { glyph: 's', upperGlyph: 'S', color: 'finger-4', size: 'key', code: 83 },
                { glyph: 'd', upperGlyph: 'D', color: 'finger-3', size: 'key', code: 68 },
                { glyph: 'f', upperGlyph: 'F', color: 'finger-2-left', size: 'key', code: 70 },
                { glyph: 'g', upperGlyph: 'G', color: 'finger-2-left', size: 'key', code: 71 },
                { glyph: 'h', upperGlyph: 'H', color: 'finger-2-right', size: 'key', code: 72 },
                { glyph: 'j', upperGlyph: 'J', color: 'finger-2-right', size: 'key', code: 74 },
                { glyph: 'k', upperGlyph: 'K', color: 'finger-3', size: 'key', code: 75 },
                { glyph: 'l', upperGlyph: 'L', color: 'finger-4', size: 'key', code: 76 },
                { glyph: ';', upperGlyph: ':', color: 'finger-5', size: 'key', code: 186 },
                { glyph: '\'', upperGlyph: '"', color: 'finger-5', size: 'key', code: 222 },
                { glyph: 'Enter', upperGlyph: 'Enter', color: 'grey', size: 'command', code: 13 },
            ],
            [
                { glyph: 'Shift', upperGlyph: 'Shift', color: 'grey', size: 'command', code: 16 },
                { glyph: 'z', upperGlyph: 'Z', color: 'finger-5', size: 'key', code: 90 },
                { glyph: 'x', upperGlyph: 'X', color: 'finger-4', size: 'key', code: 88 },
                { glyph: 'c', upperGlyph: 'C', color: 'finger-3', size: 'key', code: 67 },
                { glyph: 'v', upperGlyph: 'V', color: 'finger-2-left', size: 'key', code: 86 },
                { glyph: 'b', upperGlyph: 'B', color: 'finger-2-left', size: 'key', code: 66 },
                { glyph: 'n', upperGlyph: 'N', color: 'finger-2-right', size: 'key', code: 78 },
                { glyph: 'm', upperGlyph: 'M', color: 'finger-2-right', size: 'key', code: 77 },
                { glyph: ',', upperGlyph: '<', color: 'finger-3', size: 'key', code: 188 },
                { glyph: '.', upperGlyph: '>', color: 'finger-4', size: 'key', code: 190 },
                { glyph: '/', upperGlyph: '?', color: 'finger-5', size: 'key', code: 191 },
                { glyph: 'Shift', upperGlyph: 'Shift', color: 'grey', size: 'command', code: 16 },
            ], [
                { glyph: 'Ctrl', upperGlyph: 'Ctrl', color: 'grey', size: 'key', code: 17 },
                { glyph: '', upperGlyph: '', color: 'grey', size: 'key' },
                { glyph: 'Alt', upperGlyph: 'Alt', color: 'grey', size: 'key', code: 18 },
                { glyph: ' ', upperGlyph: '', color: 'grey', size: 'space', code: 32 },
                { glyph: 'Alt', upperGlyph: 'Alt', color: 'grey', size: 'key', code: 18 },
                { glyph: '', upperGlyph: '', color: 'grey', size: 'key' },
                { glyph: 'Ctrl', upperGlyph: 'Ctrl', color: 'grey', size: 'key', code: 17 }
            ]
        ],
    "ru":
        [
            [
                { glyph: 'ё', upperGlyph: 'Ё', color: 'finger-5', size: 'small', code: 192 },
                { glyph: '1', upperGlyph: '!', color: 'finger-5', size: 'key', code: 49 },
                { glyph: '2', upperGlyph: '"', color: 'finger-4', size: 'key', code: 50 },
                { glyph: '3', upperGlyph: '№', color: 'finger-3', size: 'key', code: 51 },
                { glyph: '4', upperGlyph: ';', color: 'finger-2-left', size: 'key', code: 52 },
                { glyph: '5', upperGlyph: '%', color: 'finger-2-left', size: 'key', code: 53 },
                { glyph: '6', upperGlyph: ':', color: 'finger-2-left', size: 'key', code: 54 },
                { glyph: '7', upperGlyph: '?', color: 'finger-2-right', size: 'key', code: 55 },
                { glyph: '8', upperGlyph: '*', color: 'finger-3', size: 'key', code: 56 },
                { glyph: '9', upperGlyph: '(', color: 'finger-4', size: 'key', code: 57 },
                { glyph: '0', upperGlyph: ')', color: 'finger-5', size: 'key', code: 48 },
                { glyph: '-', upperGlyph: '_', color: 'finger-5', size: 'key', code: 189 },
                { glyph: '=', upperGlyph: '+', color: 'finger-5', size: 'key', code: 187 },
                { glyph: 'Backspace', upperGlyph: 'Backspace', color: 'grey', size: 'command', code: 8 }
            ],
            [
                { glyph: 'Tab', upperGlyph: 'Tab', color: 'grey', size: 'command', code: 9 },
                { glyph: 'й', upperGlyph: 'Й', color: 'finger-5', size: 'key', code: 81 },
                { glyph: 'ц', upperGlyph: 'Ц', color: 'finger-4', size: 'key', code: 87 },
                { glyph: 'у', upperGlyph: 'У', color: 'finger-3', size: 'key', code: 69 },
                { glyph: 'к', upperGlyph: 'К', color: 'finger-2-left', size: 'key', code: 82 },
                { glyph: 'е', upperGlyph: 'Е', color: 'finger-2-left', size: 'key', code: 84 },
                { glyph: 'н', upperGlyph: 'Н', color: 'finger-2-right', size: 'key', code: 89 },
                { glyph: 'г', upperGlyph: 'Г', color: 'finger-2-right', size: 'key', code: 85 },
                { glyph: 'ш', upperGlyph: 'Ш', color: 'finger-3', size: 'key', code: 73 },
                { glyph: 'щ', upperGlyph: 'Щ', color: 'finger-4', size: 'key', code: 79 },
                { glyph: 'з', upperGlyph: 'З', color: 'finger-5', size: 'key', code: 80 },
                { glyph: 'х', upperGlyph: 'Х', color: 'finger-5', size: 'key', code: 219 },
                { glyph: 'ъ', upperGlyph: 'Ъ', color: 'finger-5', size: 'key', code: 221 },
                { glyph: '\\', upperGlyph: '/', color: 'grey', size: 'command', code: 220 },
            ],
            [
                { glyph: 'Caps Lock', upperGlyph: 'Caps Lock', color: 'grey', size: 'command', code: 20 },
                { glyph: 'ф', upperGlyph: 'Ф', color: 'finger-5', size: 'key', code: 65 },
                { glyph: 'ы', upperGlyph: 'Ы', color: 'finger-4', size: 'key', code: 83 },
                { glyph: 'в', upperGlyph: 'В', color: 'finger-3', size: 'key', code: 68 },
                { glyph: 'а', upperGlyph: 'А', color: 'finger-2-left', size: 'key', code: 70 },
                { glyph: 'п', upperGlyph: 'П', color: 'finger-2-left', size: 'key', code: 71 },
                { glyph: 'р', upperGlyph: 'Р', color: 'finger-2-right', size: 'key', code: 72 },
                { glyph: 'о', upperGlyph: 'О', color: 'finger-2-right', size: 'key', code: 74 },
                { glyph: 'л', upperGlyph: 'Л', color: 'finger-3', size: 'key', code: 75 },
                { glyph: 'д', upperGlyph: 'Д', color: 'finger-4', size: 'key', code: 76 },
                { glyph: 'ж', upperGlyph: 'Ж', color: 'finger-5', size: 'key', code: 186 },
                { glyph: 'э', upperGlyph: 'Э', color: 'finger-5', size: 'key', code: 222 },
                { glyph: 'Enter', upperGlyph: 'Enter', color: 'grey', size: 'command', code: 13 },
            ],
            [
                { glyph: 'Shift', upperGlyph: 'Shift', color: 'grey', size: 'command', code: 16 },
                { glyph: 'я', upperGlyph: 'Я', color: 'finger-5', size: 'key', code: 90 },
                { glyph: 'ч', upperGlyph: 'Ч', color: 'finger-4', size: 'key', code: 88 },
                { glyph: 'с', upperGlyph: 'С', color: 'finger-3', size: 'key', code: 67 },
                { glyph: 'м', upperGlyph: 'М', color: 'finger-2-left', size: 'key', code: 86 },
                { glyph: 'и', upperGlyph: 'И', color: 'finger-2-left', size: 'key', code: 66 },
                { glyph: 'т', upperGlyph: 'Т', color: 'finger-2-right', size: 'key', code: 78 },
                { glyph: 'ь', upperGlyph: 'Ь', color: 'finger-2-right', size: 'key', code: 77 },
                { glyph: 'б', upperGlyph: 'Б', color: 'finger-3', size: 'key', code: 188 },
                { glyph: 'ю', upperGlyph: 'Ю', color: 'finger-4', size: 'key', code: 190 },
                { glyph: '.', upperGlyph: ',', color: 'finger-5', size: 'key', code: 191 },
                { glyph: 'Shift', upperGlyph: 'Shift', color: 'grey', size: 'command', code: 16 },
            ], [
                { glyph: 'Ctrl', upperGlyph: 'Ctrl', color: 'grey', size: 'key', code: 17 },
                { glyph: '', upperGlyph: '', color: 'grey', size: 'key' },
                { glyph: 'Alt', upperGlyph: 'Alt', color: 'grey', size: 'key', code: 18 },
                { glyph: ' ', upperGlyph: '', color: 'grey', size: 'space', code: 32 },
                { glyph: 'Alt', upperGlyph: 'Alt', color: 'grey', size: 'key', code: 18 },
                { glyph: '', upperGlyph: '', color: 'grey', size: 'key' },
                { glyph: 'Ctrl', upperGlyph: 'Ctrl', color: 'grey', size: 'key', code: 17 }
            ]
        ]
};

const keys = (language = "en") => {
    return keySets[language];
};

export default keys;
